name: carreno_post2_u9
description: "Widget Tests y Golden Tests - Unidad 9 Aplicaciones Móviles"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  bloc_test: ^9.1.7
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true